# peers are the replicas which act as both recorders and proposers. clients are the clients
# name and ip:port should be unique
# to add more peers or clients: add new lines following the same structure
peers:
  - name: 0
    ip: 10.156.33.140
    proxyport: 9000
    recorderport: 9001
  - name: 1
    ip: 10.156.33.141
    proxyport: 9002
    recorderport: 9003
  - name: 2
    ip: 10.156.33.142
    proxyport: 9004
    recorderport: 9005
  - name: 3
    ip: 10.156.33.143
    proxyport: 9006
    recorderport: 9007
  - name: 4
    ip: 10.156.33.144
    proxyport: 9008
    recorderport: 9009

clients:
  - name: 21
    ip: 10.156.33.145
    clientport: 10000
  - name: 22
    ip: 10.156.33.146
    clientport: 10001
  - name: 23
    ip: 10.156.33.147
    clientport: 10002
  - name: 24
    ip: 10.156.33.148
    clientport: 10003
  - name: 25
    ip: 10.156.33.149
    clientport: 10004