peers:
  - name: 0
    address: 0.0.0.0:9000
  - name: 1
    address: 0.0.0.0:9001
  - name: 2
    address: 0.0.0.0:9002
  - name: 3
    address: 0.0.0.0:9003
  - name: 4
    address: 0.0.0.0:9004
clients:
  - name: 5
    address: 0.0.0.0:10000
  - name: 6
    address: 0.0.0.0:10001
  - name: 7
    address: 0.0.0.0:10002
  - name: 8
    address: 0.0.0.0:10003
  - name: 9
    address: 0.0.0.0:10004
