peers:
   - name: 1
     ip: 0.0.0.0
     proxyport: 9001
     recorderport: 10001
   - name: 2
     ip: 0.0.0.0
     proxyport: 9002
     recorderport: 10002
   - name: 3
     ip: 0.0.0.0
     proxyport: 9003
     recorderport: 10003
   - name: 4
     ip: 0.0.0.0
     proxyport: 9004
     recorderport: 10004
   - name: 5
     ip: 0.0.0.0
     proxyport: 9005
     recorderport: 10005

clients:
   - name: 21
     ip: 0.0.0.0
     clientport: 11001
   - name: 22
     ip: 0.0.0.0
     clientport: 11002
   - name: 23
     ip: 0.0.0.0
     clientport: 11003
   - name: 24
     ip: 0.0.0.0
     clientport: 11004
   - name: 25
     ip: 0.0.0.0
     clientport: 11005
